version: "3.8"

services:
  backend:
    build:
      context: Server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: RigBuildClient
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
